---
# - hosts: oldserver
#   gather_facts: true
#   roles:
#   - backup

- hosts: newserver
  gather_facts: true
  roles:
  # - create_user
  # - nginx
  # - certbot
  # - php_fpm
  # - mysql
  - default_software


# - hosts: localhost
#   gather_facts: false
#   roles:
#   - simplecloud_dns