---

  - name: Install epel-release on CentOS
    yum:
      name: epel-release
      state: present
      update_cache: yes
    when: ansible_facts['distribution'] == "CentOS"

  - name: Install needed packages on CentOS
    yum:
      name: "{{ CentOS.packages }}"
      state: present
      update_cache: yes
    when: ansible_facts['distribution'] == "CentOS"

  - name: Install needed packages on Debian-based
    apt:
      name: "{{ Debian.packages }}"
      state: present
      update_cache: yes
      autoclean: yes
      autoremove: yes
    when: ansible_facts['os_family'] == "Debian"
