---

  - name: Install epel-release on CentOS
    yum:
      name: epel-release
      state: present
      update_cache: yes
    when: ansible_facts['distribution'] == "CentOS"

  - name: Install needed packages on CentOS
    yum:
      name: "{{ CentOS.packages }}"
      state: present
      update_cache: yes
    when: ansible_facts['distribution'] == "CentOS"

  - name: Install needed packages on Debian-based
    apt:
      name: "{{ Debian.packages }}"
      state: present
      update_cache: yes
      autoclean: yes
      autoremove: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Set nginx.conf
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: Copy standart snippet for php site
    template:
      src: snippets/standart-sites.conf.j2
      dest: /etc/nginx/snippets/standart-sites.conf
    notify:
      - reload nginx

  - name: Copy default config
    template:
      src: default.conf.j2
      dest: /etc/nginx/sites-available/default

  - name: Enable default site
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
    notify:
      - reload nginx

  - name: Add phpinfo
    copy:
      src: index.php
      dest: /var/www/html/index.php

# MySQL Configuration
  - name: Sets the root password
    mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Removes all anonymous user accounts
    mysql_user:
      name: ''
      host_all: yes
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Removes the MySQL test database
    mysql_db:
      name: test
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
